output:
  sort-by: name
  output: table
  sections:
    show:
      - providers
  file: README.md

diagram:
  enabled: true
  output: diagram.svg
  provider: mermaid
  direction: TD  # Top-Down direction (can also use LR for Left-Right)
  cluster: false  # Group resources by module
  embed: false    # Embed diagram in markdown output
  titles: false   # Show resource type titles