formatter: "markdown table"

output:
  sort-by: name
  sections:
    show:
      - providers
  file: README.md

diagram:
  enabled: true
  output: diagram.svg
  provider: mermaid
  direction: TD # Top-Down direction (can also use LR for Left-Right)
  cluster: false # Group resources by module
  embed: false # Embed diagram in markdown output
  titles: false # Show resource type titles